# Generated by Django 5.0.3 on 2024-03-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_todoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='author',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
