# Generated by Django 5.0.3 on 2024-03-05 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_alter_todoitem_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
